@ #33 | create provider manager
teracyhq-incubator/teracy-dev-core pull request #41
Opened 2018-10-22 18:06 UTC by hieptranquoc

connect #33 
please check this PR. Thank you!

2018-10-22 18:54 UTC, hieptranquoc commented
@hoatle @datphan, please help me review this PR!

2018-10-23 01:57 UTC, hoatle requested changes
@hieptranquoc make sure to study and understand how everything is connected and works to implement the requirements precisely and  properly

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core.rb
>    end
Let's add public api for the TeracyDevCore:

TeracyDevCore.register_provider(provider_type: String, provider: Provider)

TeracyDevCore.register_provider is the proxy to the TeracyDevCore::Providers::Manager

Providers::Manager is a static class that holds the registered providers (registry = {"x_type": [x_provider_impl]})
Providers::Manager allows other classes to access the registry

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/config/provider.rb
> +      attr_reader :providerManager
remove this

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/config/provider.rb
> +        @providerManager = TeracyDevCore::Providers::Manager.new
```ruby
registry = Providers::Manager.registry

providers_settings.each do |provider_settings|
  next if !provider_settings['enabled']
  providers = registry(provider_settings['type'])
  # TODO: check if there is any provider implementation registered
  # if not, add warning and next
  providers.each do |provider|
    provider.configure(provider_settings, config)
  end
end
```

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +      def register(provider_type)
```ruby
      def register(provider_type, provider_impl)
        # make sure provider_impl must implement the configure method (Provider interface)
        registry[provider_type] = [provider_impl] if registry[provider_type] is nil
        registry[provider_type] << provider_impl
      end
```

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        when 'virtualbox'
we never know beforehand the type of providers, this is considered hard-code and not understanding the flow.

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/providers/provider.rb
> +      def configure_provider(settings, config)
def configure(provider_settings, node_config)

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/providers/virtualbox.rb
> +      def configure_provider(settings, config)
configure(provider_settings, node_config)

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core/providers/vmware.rb
> +      def configure_provider(settings, config)
def configure(provider_settings, node_config)

2018-10-23 01:57 UTC, hoatle commented on lib/teracy-dev-core.rb
>      TeracyDev.register_configurator(TeracyDevCore::Config::WinSSH.new)
```
self.register_provider("virtualbox", TeracyDevCore::Config::VirtualBoxProvider.new)
self.register_provider("vmware_desktop", TeracyDevCore::Config::VMwareProvider.new)
```

2018-10-25 12:41 UTC, hoatle commented on lib/teracy-dev-core.rb
>    end
@hieptranquoc check my updated comment here

2018-10-25 18:02 UTC, hieptranquoc commented
@hoatle I've updated! please check again.

2018-10-25 18:13 UTC, hoatle requested changes
@hieptranquoc pls check my comments

2018-10-25 18:13 UTC, hoatle commented on lib/teracy-dev-core/config/provider.rb
> +            @logger.warn("#{provider_settings['type']} have not registered")
`@logger.warn("not any provider with the type of #{provider_settings['type']} is registered")`

2018-10-25 18:13 UTC, hoatle commented on lib/teracy-dev-core/config/provider.rb
> +          if providers.nil?
nil? or is an empty array?

2018-10-25 18:13 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @@logger.debug("provider: #{provider_type} registered")
```
@@logger.debug("#{provider_impl} with type: #{provider_type} registered")
```

2018-10-25 18:13 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @registry[provider_type] = [provider_impl] if @registry[provider_type].nil?
validate provider_impl that must implement the configure method signature

2018-10-25 18:28 UTC, hieptranquoc commented
@hoatle I've updated! Please check again! Thank you!

2018-10-25 18:32 UTC, hoatle commented on lib/teracy-dev-core/config/provider.rb
> +            break
why `break` here?

2018-10-25 18:43 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @registry[provider_type] << provider_impl
bug here:

```
[TeracyDevCore::Providers::Manager][DEBUG]: registry: {"virtualbox"=>[#<TeracyDevCore::Providers::VirtualBox:0x00000001020eaf80 @logger=#<Logger:0x00000001020eaf30 @level=0, @progname="TeracyDevCore::Providers::VirtualBox", @default_formatter=#<Logger::Formatter:0x00000001020eadf0 @datetime_format=nil>, @formatter=#<Proc:0x00000001020eab98@/Users/hoatle/teracy-dev/lib/teracy-dev/logging.rb:44>, @logdev=#<Logger::LogDevice:0x00000001020ead28 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00000001020eacd8>>>>, #<TeracyDevCore::Providers::VirtualBox:0x00000001020eaf80 @logger=#<Logger:0x00000001020eaf30 @level=0, @progname="TeracyDevCore::Providers::VirtualBox", @default_formatter=#<Logger::Formatter:0x00000001020eadf0 @datetime_format=nil>, @formatter=#<Proc:0x00000001020eab98@/Users/hoatle/teracy-dev/lib/teracy-dev/logging.rb:44>, @logdev=#<Logger::LogDevice:0x00000001020ead28 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00000001020eacd8>>>>], "vmware_desktop"=>[#<TeracyDevCore::Providers::VMware:0x0000000101266798 @logger=#<Logger:0x0000000101267440 @level=0, @progname="TeracyDevCore::Providers::VMware", @default_formatter=#<Logger::Formatter:0x00000001008578b0 @datetime_format=nil>, @formatter=#<Proc:0x00000001008541b0@/Users/hoatle/teracy-dev/lib/teracy-dev/logging.rb:44>, @logdev=#<Logger::LogDevice:0x00000001008571a8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000100856f50>>>>, #<TeracyDevCore::Providers::VMware:0x0000000101266798 @logger=#<Logger:0x0000000101267440 @level=0, @progname="TeracyDevCore::Providers::VMware", @default_formatter=#<Logger::Formatter:0x00000001008578b0 @datetime_format=nil>, @formatter=#<Proc:0x00000001008541b0@/Users/hoatle/teracy-dev/lib/teracy-dev/logging.rb:44>, @logdev=#<Logger::LogDevice:0x00000001008571a8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000100856f50>>>>]}
/Users/hoatle/teracy-dev/workspace/teracy-dev-core/lib/teracy-dev-core/providers/manager.rb:23:in `register'
```

2018-10-25 18:43 UTC, hieptranquoc commented
@hoatle I've updated!

2018-10-25 18:44 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @registry[provider_type] << provider_impl
one provider_impl was registered into the registry twice, this is a bug

2018-10-25 18:44 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @registry[provider_type] << provider_impl
logging with debug should help, try to use the debug log where we should use to check the changes.

2018-10-25 18:47 UTC, hoatle commented on lib/teracy-dev-core/providers/manager.rb
> +        @registry[provider_type] << provider_impl
```ruby
      def self.register(provider_type, provider_impl)
        if !provider_impl.respond_to?(:configure)
          @logger.warn("provider #{provider_impl} must implement configure method, ignored")
          return
        end

        if @registry[provider_type].nil?
          @registry[provider_type] = [provider_impl]
        else
          @registry[provider_type] << provider_impl
        end
        @@logger.debug("#{provider_impl} with type: #{provider_type} registered")
        @@logger.debug("registry: #{@registry}")
      end
```

2018-10-25 18:57 UTC, hieptranquoc commented
@hoatle I've fixed, please check again! Thank you so so much!

2018-10-25 19:00 UTC, hoatle approved these changes
LGTM, merging, will do some minor clean up

2018-10-25 19:01 UTC, merged