Task/#12 update readme
teracyhq-incubator/teracy-dev-core pull request #63
Opened 2019-01-23 10:41 UTC by hieptranquoc

connect #12 
please check this PR! Thank you.

*** Note: I applied all comment from PR https://github.com/teracyhq-incubator/teracy-dev-core/pull/32.

2019-01-23 10:47 UTC, hieptranquoc commented
preview: https://github.com/hieptranquoc/teracy-dev-core/tree/task/%2312-update-README

2019-01-30 03:42 UTC, hoavt submitted a review, later dismissed

2019-01-30 03:59 UTC, hoatle requested changes
@hieptranquoc @hoavt please check my comments.

Need @phuonglm and @datphan to review on this to make sure we don't miss anything, the README file here is very important so that everyone must approve before merging.

2019-01-30 03:59 UTC, hoatle commented on README.md
> +# Teracy-dev-core
keep the extension name

2019-01-30 03:59 UTC, hoatle commented on README.md
> +To override the built-in config, create `workspace/teracy-dev-entry/config_override.yaml` with the
config_default.yaml

config_override.yaml should be used only by users on their own to override the existing config.

2019-01-30 03:59 UTC, hoatle commented on README.md
> +- Use latest stable version (auto update):
I don't see the reason to change order here, all the README has the same order, so don't make them inconsistent.
(https://github.com/teracyhq-incubator/teracy-dev-essential#how-to-use https://github.com/teracyhq-incubator/teracy-dev-certs#how-to-use)

2019-01-30 03:59 UTC, hoatle commented on README.md
> +- Run `vagrant up` or `vagrant reload --provision` (if your vagrant machine is running) to apply your configure.
your configuration

2019-01-30 03:59 UTC, hoatle commented on README.md
> +- Run `vagrant up` or `vagrant reload --provision` (if your vagrant machine is running) to apply your configure.
your configuration

2019-01-30 03:59 UTC, hoatle commented on README.md
> +## Prerequisites
specify the required teracy-dev version from https://github.com/teracyhq-incubator/teracy-dev-core/blob/develop/manifest.yaml

2019-01-30 03:59 UTC, hoatle commented on README.md
> +- Follow the guide at https://github.com/teracyhq/dev/blob/develop/docs/getting_started.rst to set up `teracy-dev`.
move this to the `how to use` section instead

2019-01-30 03:59 UTC, hoatle commented on README.md
> +  * [Example for variables](https://github.com/teracyhq-incubator/teracy-dev-core/tree/develop/docs/examples/variables.yaml)
use relative links so that when we git tag or change branch, it should point to the docs at that branch/tag.

2019-01-30 03:59 UTC, hoatle commented on README.md
> +  * Example:
Examples:

2019-01-30 08:49 UTC, hieptranquoc commented
@hoatle I've applied all your comment! Please check this PR again! Thank you

2019-01-30 08:54 UTC, hoatle commented
@phuonglm @datphan @hoavt please review

2019-01-30 10:02 UTC, datphan reviewed
pls check my comments

2019-01-30 10:02 UTC, datphan commented on docs/examples/multi-nodes.yaml
> +        - _id: "public-network-0" # unique id. requirement
should be `unique id. required`

2019-01-30 10:02 UTC, datphan commented on docs/examples/multi-nodes.yaml
> +        - _id: "public-network-0" # unique id. requirement
similar for other comments like this

2019-01-30 10:02 UTC, datphan commented on docs/examples/variables.yaml
> +  some_env: ${MY_VAR:-value}-affix
```
some_env: value
```

2019-01-30 10:02 UTC, datphan commented on README.md
>  To override the built-in config, create `workspace/teracy-dev-entry/config_default.yaml` with the
To override the built-in version, ...

2019-01-31 03:24 UTC, hieptranquoc commented
I updated! Please check this PR again! Thank you.

2019-01-31 03:35 UTC, datphan submitted a review, later dismissed

2019-02-21 00:02 UTC, hoavt reviewed
@hieptranquoc Please check my comments.

2019-02-21 00:02 UTC, hoavt commented on README.md
> +The core extension for [teracy-dev](https://github.com/teracyhq/dev/tree/develop) which support all options from [vagrant](https://www.vagrantup.com/docs/)
which supports

2019-02-21 00:02 UTC, hoavt commented on README.md
>  for teracy-dev yaml config format.
for teracy-dev yaml configuration format.

2019-02-21 00:02 UTC, hoavt commented on README.md
>  By default, teracy-dev already configures to use this extension, however, you can override the
teracy-dev is already configured

2019-02-21 00:02 UTC, hoavt commented on README.md
>  config with your own, for example, to use a different version or a forked repo.
you can override the configuration

2019-02-21 00:02 UTC, hoavt commented on README.md
> +## Supported configuration
configurations

2019-02-21 00:02 UTC, hoavt commented on README.md
> +These are the supported configuration in teracy-dev-core, you can configure in `workspace/teracy-dev-entry/config_override.yaml`:
configurations.... you can configure them in the...... yaml` file:

2019-02-21 00:02 UTC, hoavt commented on README.md
> +  * `variables` is used to define dynamic configuration values for use in configuration files. After setting, you can call them by `%{env_key}`.
are used....
After setting them.....

2019-03-19 08:52 UTC, hieptranquoc commented
I've applied all comments, please check this PR again. Thank you!

2019-03-19 10:30 UTC, hoatle commented
@phuonglm please review then

2019-04-08 05:22 UTC, phuonglm commented
The doc and example look ok for me.

2019-04-08 05:22 UTC, phuonglm approved these changes

2019-04-08 05:23 UTC, hoatle commented
merging then.

2019-04-08 05:23 UTC, merged